### ISSUE TITLE
Data Lake measurements endpoint returns no data series when no data between `startDate` and `endDate`

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1329] opened 2023-02-20 17:58 UTC
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Backend

### What happened?

The endpoint for data lake measurements allows to filter the data records when querying for a specific measurement.
Hereby, you define a time window for which you want to get data by specifying `startDate` and `endDate`.
If you choose both parameters so that there are no records matching your criterion in the data lake, the API returns no data series in the response like the whole measurement would not exist.

### How to reproduce?

Query the API endpoint `/api/v4/datalake/measurements/<identifier>` and extend the query by `?startDate=valueStart&endDate=valueEnd`. 
Choose `valueStart` and `valueEnd` in such way that there are no entries for targeted measurement in the corresponding time frame.
Eventually, the API returns a response with no data series indicating the whole measurement does not exist.

### Expected behavior

Return the metadata of the data series but with an empty array for `rows` so that it clearly indicates that the actual measurement exists but there is to data available for the given query.

### Are you willing to submit a PR?

None

**Comment by SteveYurongSu** [comment] 2023-02-21 18:39
I'd like to take a look :)

Please assign it to me @bossenti

**Comment by SteveYurongSu** [comment] 2023-02-21 18:39
I'd like to take a look :)

Please assign it to me @bossenti

**Comment by SteveYurongSu** [comment] 2023-02-25 17:30
I have done some experiments these days and found that the reason why the API returns a response indicating the whole measurement does not exist when no data between startDate and endDate:

**The InfluxDB client always returns a response with no metadata when querying a timeline with no data between startDate and endDate (even if the timeline exists).** 

So, there seems to be some difficulty in achieving the expected behavior. In fact, I have some immature solutions in my mind. But in my solutions, at least one query call of Influxdb needs to be added in `DataExplorerQueryV4#executeQuery`, which may also cause additional problems... 

I'm not sure what to do next now.  @bossenti What do you think? 😂😂

**Comment by bossenti** [comment] 2023-02-26 12:56
Thanks for investigating @SteveYurongSu!

Hm, if that's the standard behavior of the influx client, this might be fine as it is🤔 

What would be the expected behavior for you?

**Comment by bossenti** [comment] 2023-03-01 09:39
Okay good to know 🤔 
Frankly, I would refrain from building here something custom to get the expected behavior since we might exchange the influxdb in future...
Let's start a discussion about this on the mailing list soon 🙂 
So if you are fine with it @SteveYurongSu I would close this as `wont fix`.

**Comment by tenthe** [comment] 2023-03-01 09:41
+1 for starting a discussion about the pros and cons of inlfluxdb and comparing it with iotdb

**Comment by SteveYurongSu** [comment] 2023-03-01 18:00
> So if you are fine with it @SteveYurongSu I would close this as wont fix.

I'm fine with the influxdb's behaviour. Let's close it as wont-fix. 🙂 @bossenti 

> +1 for starting a discussion about the pros and cons of inlfluxdb and comparing it with iotdb

+1 from my side too :) @tenthe

**Closed** 2023-03-01 21:57 UTC
Labels: bug, wontfix, backend
