### ISSUE TITLE
Support array types for OPC UA

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1693] opened 2023-06-16 06:33 UTC
Currently, the OPC UA adapter lacks support for arrays. OPC UA allows for the representation of data using basic data types as well as arrays. However, the current implementation of the adapter does not handle arrays properly in the events.

Details can be found in this discussion:
_Originally posted by @curichan in https://github.com/apache/streampipes/discussions/1650#discussioncomment-6170814_

**Comment by bossenti** [comment] 2023-10-19 16:52
duplicate of #1980

**Closed by bossenti** 2023-10-19 16:52 UTC
Labels: duplicate, enhancement, connect

**Comment by bossenti** [comment] 2024-04-17 11:24
Issue still persists, see #2736
