### ISSUE TITLE
Refactor processing elements

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#775] opened 2022-11-26 15:34 UTC
Refactor Pipeline elements from three-class approach to one class approach.

Imported from Jira [STREAMPIPES-615](https://issues.apache.org/jira/browse/STREAMPIPES-615). Original Jira may contain additional context.
Reported by: bossenti.

**Comment by dominikriemer** [comment] 2022-11-26 15:34
The following subtask(s) are associated with this issue: #776, #777

**Comment by bossenti** [comment] 2023-05-05 17:54
Is a duplicate of #1315

**Closed by bossenti** 2023-05-05 17:54 UTC
Labels: enhancement, pipeline elements, migrated from jira
