### ISSUE TITLE
Incompatible pydantic dependency in python client package

### ISSUE THREAD

**Issue by obermeier** [apache/streampipes#1944] opened 2023-09-18 19:07 UTC
### Apache StreamPipes version

0.92.0

### Affected StreamPipes components

Backend

### What happened?

Hello, when I install the StreamPipes Python client using the command `pip install streampipes`, I encounter a runtime error with the following message:
```PydanticUserError: `regex` is removed. use `pattern` instead```

This error is due to the incompatibility between versions 1.x and 2.x of pydantic.

Is this still an issue or will it be resolved in the next release with [ this line](https://github.com/apache/streampipes/blob/f44f50307f9c62552f1ec90a3a155fb40ab242fa/streampipes-client-python/pyproject.toml#L60)?

### How to reproduce?

Run `pip install streampipes` on a clean env and connect to a StreamPipes instance.

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by bossenti** [comment] 2023-09-19 05:41
@obermeier thanks for reporting this!

This is caused by pydantic's (more or less) recent release of version 2. We've already fixed this in the [development version](https://github.com/apache/streampipes/blob/dev/streampipes-client-python/pyproject.toml#L60). If you install the current dev version via `pip install git+https://github.com/apache/streampipes.git#subdirectory=streampipes-client-python` this error shouldn't occur anymore.
If you can confirm, I will close this issue.

I'm already planning to make the client compatible with pydantic `v1` and `v2`.

**Comment by obermeier** [comment] 2023-09-19 06:56
@bossenti It works 
Thank you!

**Closed** 2023-09-19 07:20 UTC
Labels: bug
