### ISSUE TITLE
problem starting adapter

### ISSUE THREAD

**Issue by sam-niag** [apache/streampipes#1755] opened 2023-07-10 12:31 UTC
### Apache StreamPipes version

Other StreamPipes version (please specify below)

### Affected StreamPipes components

Connect

### What happened?

Hi,

When creating and an MQTT adapter, I can have the schema recognized, but the MQTT adapter would not start. This is SP 0.92.0

<img width="1337" alt="Capture d’écran 2023-07-10 à 10 27 42" src="https://github.com/apache/streampipes/assets/137799900/efe4e056-3c14-4d1e-b028-1b628beed19e">

### How to reproduce?

I create a new MQTT adapter
<img width="1153" alt="Capture d’écran 2023-07-10 à 10 30 57" src="https://github.com/apache/streampipes/assets/137799900/2f9c353f-320d-4e29-8571-579252faf1c2">
<img width="1160" alt="Capture d’écran 2023-07-10 à 10 31 12" src="https://github.com/apache/streampipes/assets/137799900/341cf050-eb43-4113-ae96-0908281e84ea">
<img width="1159" alt="Capture d’écran 2023-07-10 à 10 31 23" src="https://github.com/apache/streampipes/assets/137799900/89b725d0-eb84-4710-bc95-1ca254401c11">
The schema is guessed correctly, so the iiot connector works fine
<img width="1240" alt="Capture d’écran 2023-07-10 à 10 32 22" src="https://github.com/apache/streampipes/assets/137799900/0621e261-1907-4a6c-b64d-8bc0f1086f3d">
But the adapter is not created : UI runs forever waiting for the adapter to be started
<img width="1845" alt="Capture d’écran 2023-07-10 à 10 59 14" src="https://github.com/apache/streampipes/assets/137799900/0a84bff4-49ac-4167-b0d4-366458af4888">
And there is an error and a timeout in backend log : 
<img width="1543" alt="Capture d’écran 2023-07-10 à 11 02 47" src="https://github.com/apache/streampipes/assets/137799900/584254ca-f5b0-4220-b2a6-9cb1cb78f9c3">

### Expected behavior

Expected behavior is Adapter to be successfully created and started.

### Additional technical information

SP 0.92.0 runs in docker compose on an Ubuntu host ; browser is Chrome on a Mac

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by bossenti** [comment] 2023-07-10 15:38
Hi @sam-niag,

thanks to your detailed error description, I already have a suspicion what your problem is.
Within the the third step of the adapter creation (`Configure fields`) , a warning with respect to the timestamp is shown. Did you resolve that?
If not, this may be the root cause. Please ensure that the timestamp field is configured as such:
<img width="716" alt="image" src="https://github.com/apache/streampipes/assets/50115603/8cab243b-1e72-490b-88fe-7ad211d23d2c">

Then the timestamp field should look like the following:
<img width="1245" alt="image" src="https://github.com/apache/streampipes/assets/50115603/bf80c7da-2d3a-48b6-a1b9-0f8c41d0d2a5">

Alternatively, you can also simply add a pre-configured timestamp field by clicking the <kbd>ADD TIMESTAMP</kbd> button. Please do not forget to adapt the field name to avoid a duplicate field name.

Hope this helps 🙂

**Comment by sam-niag** [comment] 2023-07-10 15:54
Hi Tim,

Thank you for your kind response. As a matter of facts I forgot to include
the screenshot for the timestamp resolution. Yes, I had resolved it
(otherwise, I guess that I could not have validated the creation of the
adapter anyway, right ?).

Kind regards

**Comment by bossenti** [comment] 2023-07-10 17:07
Damn, would have been to easy 😅 

Thanks for your quick reply
We will have a deeper look

**Comment by tenthe** [comment] 2023-07-11 05:18
Hi @sam-niag,
I am not quite sure what the problem is because your configuration looks good. And as you stated, when the schema is guessed correctly the docker container running the adapter should work as expected.
Did you change anything in the schema configuration (e.g. remove a property)?
Is it possible that the event schema of the events on this topic changes?
Did you try to restart StreamPipes by stopping all docker containers and starting them again?

Cheers,
Philipp

**Comment by sam-niag** [comment] 2023-07-12 13:51
Hello,

Yes, I tried many things ; restarting just the backend, restarting the
adapter-iiot, restarting everything...
The event schema does not change. It is streamed by a SP instance with the
MQTT Publisher btw.

**Comment by tenthe** [comment] 2023-07-13 10:34
Hi @sam-niag,
I tried to reproduce the problem with StreamPipes (0.92.0).
For this I started a StreamPipes instance with an additional Mosquitto MQTT broker.
I created a pipeline to write to MQTT and an adapter that subscribes to this topic. Unfortunately, I could not reproduce the error.
Can you please provide the logs for the `extensions-all-jvm` container? This is the container where the adapter instance is started, maybe this will give a hint what is going wrong.

Cheers,
Philipp

**Comment by dominikriemer** [comment] 2023-07-26 20:52
Closing this since there was no reply.
@sam-niag please reopen in case the problem still occurs.

**Closed by dominikriemer** 2023-07-26 20:52 UTC
Labels: bug
